Feature/fix code i
NII-DG/dg-researchflows pull request #85
Opened 2024-11-15 01:59 UTC by ivis-ikeda

# PULL REQUEST

## Background

* vaultサーバーがメインメニューのプロセスに依存しているため、メインメニュー終了時にvaultサーバーも　停止してしまう。また、停止してしまった際に再起動する機能が実装されていない

## Main Points of Modification

* vaultサーバーを起動する際に新しいセッションを作成し、独立したプロセスとして実行する。
*  ルートトークンが存在しており、サーバーが停止している場合に再起動を行う処理を追加。

## Test

* メインメニューのカーネルを再起動した際にvaultサーバーが停止しないことを確認。
*  解析環境を一度停止した後も同じ認証情報を使用できることを確認。

## Viewpoint for Review

*

## Supplementary Information

*

## ToDo

*

2024-11-19 06:19 UTC, makio-saito requested changes
レビューしました。

2024-11-19 06:19 UTC, makio-saito commented on data_gorvernance/library/utils/vault.py
> +            self.__restrat_server()
サーバー再起動した場合、ルートトークンが作り直されるはずなので、古いルートトークンを返すと接続できないはず

2024-11-19 06:19 UTC, makio-saito commented on data_gorvernance/library/utils/vault.py
> +        stdout=subprocess.DEVNULL,
ログを出すなら標準エラー出力だけでなく、標準出力も出した方がいい

2024-11-19 06:19 UTC, makio-saito commented on data_gorvernance/library/utils/vault.py
> +        # 起動処理が終わるまで少し待機
サーバー起動が1秒以内に終わるとは限らない
1秒以内に終わらないと、起動していない状態で以降の処理を行うことになる

2024-11-19 06:19 UTC, makio-saito commented on data_gorvernance/library/utils/vault.py
> +    def __is_vault_server_running(self) -> bool:
稼働していない状態は、
・プロセスは生きているが何らかの原因で応答しない
・プロセスそのものが死んでいる
の2種類考えられるけど、どっちも対応できている？

2024-11-19 06:44 UTC, ivis-ikeda commented on data_gorvernance/library/data/vault-config.hcl
> +log_file  = "/home/jovyan/.vault/log//vault.log"
/を一つ削除しました。

2024-11-19 08:22 UTC, ivis-ikeda commented on data_gorvernance/library/utils/vault.py
> +        # 起動処理が終わるまで少し待機
サーバー起動後に状態を確認する処理を追加し、一定回数失敗した場合はエラーを吐くようにしました。

2024-11-20 00:52 UTC, ivis-ikeda commented on data_gorvernance/library/utils/vault.py
> +    def __is_vault_server_running(self) -> bool:
サーバーの状態を確認する方法を修正しました。

2024-11-20 01:13 UTC, ivis-ikeda commented on data_gorvernance/library/utils/vault.py
> +        stdout=subprocess.DEVNULL,
標準出力と標準エラーの両方をログファイルに書き込むように変更しました。

2024-11-21 04:09 UTC, ivis-ikeda commented on data_gorvernance/library/utils/vault.py
> +        thread = threading.Thread(target=start_server)
スレットに関する処理を削除しました。

2024-11-21 07:06 UTC, ivis-ikeda commented on data_gorvernance/library/utils/vault.py
> +        """アンシールキー保存のメソッドです。
修正しました。

2024-11-21 07:09 UTC, ivis-ikeda commented on data_gorvernance/library/utils/vault.py
> +        # ルートトークンが存在しない場合はサーバーを起動して初期化する
再起動の実行箇所を変更しました。

2024-11-21 08:16 UTC, makio-saito requested changes
再レビューしました。

2024-11-21 08:16 UTC, makio-saito commented on data_gorvernance/library/utils/vault.py
> +                stdout=subprocess.PIPE,
この書き方だと、サブプロセスの標準出力/標準エラー出力がそのまま親プロセスの標準出力/標準エラー出力に出力される。つまり、セルのアウトプットに表示されることになる。
出力内容は不要で、リターンコードだけしか使わないなら、DEVNULLにする

2024-11-21 08:24 UTC, ivis-ikeda commented on data_gorvernance/library/utils/vault.py
>  def start_server():
クラス内に移動し、関数名を__launch_serverに変更しました。

2024-11-21 08:32 UTC, ivis-ikeda commented on data_gorvernance/library/utils/vault.py
> +                stdout=subprocess.PIPE,
DEVNULLに変更しました。

2024-11-21 08:32 UTC, makio-saito approved these changes

2024-11-21 08:32 UTC, merged