タスク組み換え
NII-DG/dg-researchflows pull request #87
Opened 2024-12-10 01:50 UTC by vas-fujinami

# PULL REQUEST

## Background

- ガバナンスシートをもとにタスクを組み替える

## Main Points of Modification

## Test

- 新規作成押下時(RFガバナンスシート無、ガバナンスシート有、既存のサブフロー無)
- タスクのマッピング処理(対象タスク:RF003001、RF009007)
![image](https://github.com/user-attachments/assets/c4ecdc9d-79d5-4ca9-8b12-7c8ca969b9a9)
![image](https://github.com/user-attachments/assets/7e13a76f-c148-4e0e-bc3d-965ccfb1c8e3)
![image](https://github.com/user-attachments/assets/4abe6e5a-b04a-4374-b8be-1b8d4e1aae11)
![image](https://github.com/user-attachments/assets/0e79f915-c268-47be-8683-ce01c107f75f)
![image](https://github.com/user-attachments/assets/ca9c5ce4-5e8f-499a-a1a8-7257ee230633)
![image](https://github.com/user-attachments/assets/8aade7a5-6e67-48bd-aefb-3bbcfed8ca0c)
![image](https://github.com/user-attachments/assets/26c822d8-d1d9-46e4-a2d0-afb1ae33ce30)
![image](https://github.com/user-attachments/assets/9658d63e-b72d-403e-b123-ffc538085a85)

- ガバナンスシート適用ボタン押下時(RFガバナンスシート無、ガバナンスシート無、既存のサブフロー有)
![image](https://github.com/user-attachments/assets/6e33690c-b7d8-4963-ab92-d07f0fcc59b3)
![image](https://github.com/user-attachments/assets/2daae217-0ec1-420e-85c6-f6219e34de5a)
![image](https://github.com/user-attachments/assets/4ee0a768-09ac-4671-bf01-18d3305afb60)
![image](https://github.com/user-attachments/assets/75bdb78e-3029-4dab-9cc4-57f5d2e6a999)
![image](https://github.com/user-attachments/assets/8e612218-6b5d-4e22-aa6e-2aa717e0a9ec)
![image](https://github.com/user-attachments/assets/fc1284eb-1c1e-49a6-ae0a-c98e4a25a9d6)
![image](https://github.com/user-attachments/assets/4ee5ec16-bb31-4cef-9ded-53aa729bf510)
![image](https://github.com/user-attachments/assets/84649b5a-2ea0-473d-bcc7-20392747c580)

## Viewpoint for Review

## Supplementary Information

## ToDo

2024-12-10 09:17 UTC, ivis-kondoKaho requested changes
レビューしました。修正お願いします。

2024-12-10 09:17 UTC, ivis-kondoKaho commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +                        if not hide_id in new_dict:
if hide_id not in new_dict:

2024-12-10 09:17 UTC, ivis-kondoKaho commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +    active_name(task_dir, working_path, update_sf_status._tasks)
status.jsonを更新するメソッドでファイルの用意までするのはメソッドの目的と合っていないのでやらない

2024-12-10 09:17 UTC, ivis-kondoKaho commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +    after_sf.write(update_sf_status)
二回書き込まなくていい。update_flgメソッドとupdate_dependent_taskメソッドで書き変えた後に書き込む。

2024-12-10 09:17 UTC, ivis-kondoKaho commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +def create_data_dir(abs_root, phase_name: str, data_dir_name: str) -> str:
これが必要なのは新規作成のときだけでは

2024-12-10 09:17 UTC, ivis-kondoKaho commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +def remove_file(drc_path: str):
shutil.rmtreeメソッドでいいのでは
https://note.nkmk.me/python-os-remove-rmdir-removedirs-shutil-rmtree/

2024-12-12 00:08 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +    vault.set_value(vault_key, token)
削除しました

2024-12-12 00:08 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +        govsheet_rf = {}
削除しました

2024-12-12 00:09 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +        self.current_time = datetime.datetime.now().strftime('%Y%m%d%H%M%S')
指摘通り修正しました(メソッドにはしていないです)

2024-12-12 00:09 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +                utils.remove_and_copy_file_notebook(self.abs_root, research_flow_dict, self.field_box, self.research_flow_message)
指摘通り修正しました

2024-12-12 00:10 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +    if not grdm_connect.check_permission(base_url, token, project_id):
get_tokenに権限チェックの処理をいれました

2024-12-12 00:11 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +                        if not hide_id in new_dict:
指摘通り修正しました

2024-12-12 00:12 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +    active_name(task_dir, working_path, update_sf_status._tasks)
指摘通り修正しました

2024-12-12 00:12 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +    after_sf.write(update_sf_status)
指摘通り修正しました

2024-12-12 00:14 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +def create_data_dir(abs_root, phase_name: str, data_dir_name: str) -> str:
新規作成のときだけでした
前の状態に戻しました

2024-12-12 00:14 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +def remove_file(drc_path: str):
指摘通り修正しました

2024-12-12 09:34 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +            if token and project_id:
inputメソッドで入力内容のチェックを入れていてそこでNGだった場合は入力欄を空欄にしそもそもボタンを表示しない処理にしていたのでif文以下を削除しました

2024-12-12 09:34 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +    def callback_apply_button(self, event):
作り直しの処理はrecreate_subflowにまとめました
recreate_subflowの中でRFガバナンスシートの有無を確認してあればRFガバナンスシートのバックアップ、なければガバナンスシートをRFガバナンスシートにコピーし、その後サブフロー群のバックアップを取るようにしています。

2024-12-12 09:35 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/create.py
> +            self.check_govsheet_rf(
既存のサブフローが有るときに処理を行わせるようにしました。
既存のサブフローの作り直し処理が主になるのでメソッド名もcheck_govsheet_rfからrecreate_current_subflowに変更しました
作り直しの処理は新規と適用で同じ処理をしていたのでrecreate_subflowという関数名で共通化させました

2024-12-12 09:35 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/create.py
> +        if govsheet_rf == {}:
指摘通り修正しました

2024-12-12 09:35 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +        box.append(message)
指摘通り修正しました

2024-12-12 09:35 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +def remove_and_copy_file_notebook(abs_root: str, research_flow_dict: dict, box: pn.WidgetBox, message: MessageBox):
同じメソッドにしました

2024-12-12 12:03 UTC, ivis-kondoKaho requested changes
指摘が多くなってしまったので、一旦修正お願いします。

2024-12-12 12:03 UTC, ivis-kondoKaho commented on data_gorvernance/library/main_menu/subflow_controller/create.py
> +                    self.project_id_input.value_input = ''
vaultに格納されている値を消す必要があるのはいつか？トークンの権限の確認はいつやるのか？プロジェクトの権限の確認はいつやるのか？権限チェックが通らなかった場合にそれぞれ何をしなければならないか？
全体的に考え直してみてほしい

2024-12-16 10:15 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/create.py
> +                    self.project_id_input.value_input = ''
考え直しました。

2024-12-16 10:15 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/create.py
> +        self.token = utils.get_token()
指摘通り修正しました

2024-12-16 11:20 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/create.py
> +            return
考え直しました

2024-12-16 11:21 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/create.py
> +        self.file_path = os.path.join(self.abs_root, self.remote_path)
self.govsheet_pathにしました

2024-12-16 11:21 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/create.py
> +                self.project_id = project_id
指摘通り修正しました

2024-12-16 11:22 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +                    vault.set_value('grdm_token', '')
他の指摘で修正が入りました

2024-12-16 11:22 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +        """パーソナルアクセストークンとプロジェクトIDの接続確認をするメソッドです。
指摘通り修正しました

2024-12-16 11:25 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +                self.input_button.visible = False
当初は両方の入力欄を出したときに片方のみの入力の場合は入力欄を空にしようと思っていたためにこうなっていましたが入力した内容を残してエラーメッセージを表示させるようにしました

2024-12-16 11:26 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +        self.project_id_input.param.watch(self.input, 'value')
value_inputで入力してボタンを押せるようにしましたがボタン押下時に判定した方が良いですか

2024-12-16 11:26 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +            project_id_value = utils.check_input(self.project_id_input.value_input)
それぞれでメッセージを出すようにしました

2024-12-16 11:27 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +        self.research_flow_message.update_success(msg_config.get('main_menu', 'success_govsheet'))
指摘通り修正しました

2024-12-16 11:27 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +            self.research_flow_message.update_success(msg_config.get('main_menu', 'success_govsheet'))
指摘通り修正しました

2024-12-16 11:27 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +        self.grdm.sync(self.token, self.grdm_url, self.project_id, govsheet_path, self.abs_root)
指摘通り修正しました

2024-12-16 11:27 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +        file.JsonFile(govsheet_rf_path).write(govsheet)
その通りです。else文以下を削除しインデントをあげました

2024-12-16 11:28 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/create.py
> +    def new_status_file(self, new_phase_name: str, new_subflow_id: str):
メソッド名と説明を修正しました

2024-12-16 11:28 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +def get_token() -> str:
指摘通り修正しました

2024-12-16 11:30 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +        current_time = datetime.datetime.now().strftime('%Y%m%d%H%M%S')
current_timeはrecreate_subflowメソッドで定義しましたが他はメソッド呼ぶ前の判定で使っているので難しいと思いました

2024-12-16 11:31 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +            govsheet_rf = json.load(f)
GRDMに同期はしないことで決定したため修正は行っていません

2024-12-16 11:31 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +        self.cancel_button.on_click(self.callback_cancel_button)
指摘通り修正しました

2024-12-16 11:31 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +    def file_operation(self):
指摘通り修正しました

2024-12-16 11:33 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +def remove_file(drc_path: str):
修正した後の動確でエラーが起きたので戻していました。戻したことを記載するのを忘れていました。
エラーの原因は判明し解消もしたので再度修正しています。

2024-12-16 11:34 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +    if not grdm_connect.check_permission(base_url, token, project_id):
指摘通り修正しました

2024-12-17 04:26 UTC, ivis-kondoKaho requested changes
修正お願いします

2024-12-17 04:26 UTC, ivis-kondoKaho commented on data_gorvernance/library/main_menu/main.py
> +        self.project_id_input.param.watch(self.input, 'value')
ボタン押せるようになっているなら大丈夫です

2024-12-18 07:49 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +        current_time = datetime.datetime.now().strftime('%Y%m%d%H%M%S')
元に戻しました

2024-12-18 07:49 UTC, vas-fujinami commented on data_gorvernance/library/data/message.ini
> +project_id_pattern_error = プロジェクト IDは半角英数記号('\/:*?"<>|'は除く)で入力してください
指摘通り修正しました

2024-12-18 07:51 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +        self.project_id_input.param.watch(self.input, 'value')
ボタンは押せますが入力した後1回削除するとボタンは押せる状態になったままになるので押したときに入力が無い場合の処理をいれました

2024-12-18 07:52 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +    return token
指摘通り修正しました

2024-12-18 07:53 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +                self.project_id = project_id
一旦インスタンス変数に入れておき、callback_input_buttonメソッド内でアクセス権限のチェックで通らなかったときにメッセージを出して処理終了するようにしました

2024-12-18 07:53 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +            self.log.error(f'{message}\n{traceback.format_exc()}')
削除しました

2024-12-18 07:54 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +                if utils.check_grdm_token(self.grdm_url, token):
get_tokenの中でやるので削除しました

2024-12-18 07:54 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +                    self.operation_file()
それぞれelse文を追加しました

2024-12-18 07:54 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +                    utils.is_half_width_alphanumeric_token(self.token_input.value_input)
指摘通り修正しました
project_idも1つにまとめています

2024-12-18 07:55 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +                    self.operation_file()
前の指摘と同じくelse文を追加しています

2024-12-18 07:55 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +            self.log.error(f'{message}\n{traceback.format_exc()}')
削除しました

2024-12-18 07:55 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +    def operation_file(self):
try~except文をいれました

2024-12-18 07:55 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +        for i, path in enumerate(sync_path_list):
指摘通り修正しました

2024-12-18 07:56 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/create.py
> +                    self.project_id = project_id
入力欄を表示するようにしました

2024-12-18 07:56 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/create.py
> +            self.log.error(message)
削除しました

2024-12-18 07:56 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/create.py
> +                    pass
passせずアクセス権限のチェックをするようにしました

2024-12-18 07:57 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/create.py
> +                if utils.check_grdm_access(self.grdm_url, self.token, project_id):
前の指摘と同様else文を追加しています

2024-12-18 07:57 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +    sync_path = [backup_govsheet_rf_dir]
削除しました

2024-12-18 07:58 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +            sync_path_list.append(zipdir_path)
指摘通り修正しました
バックアップも同期するのでdata_gorvernance/logディレクトリも指定して同期してます

2024-12-18 07:58 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/create.py
> +        )
同期処理を入れてます

2024-12-18 08:01 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/create.py
> +            return
recreate_current_subflowメソッドではRFガバナンスシート、ガバナンスシートの両方が無い場合にFloatPanelを表示させ、それ以外は作り直しの処理に進むようにしてます
既存のサブフロー、RFガバナンスシートが存在せずガバナンスシートが存在する場合でnew_create_subflowメソッド前にガバナンスシートをRFガバナンスシートにコピーする処理をいれました

2024-12-19 02:52 UTC, ivis-kondoKaho requested changes
修正お願いします

2024-12-19 02:52 UTC, ivis-kondoKaho commented on data_gorvernance/library/main_menu/subflow_controller/create.py
> +            self._err_output.update_error(message)
エラーが発生したときにlogを吐かないのは論外なので、ここのクラスでlogを書けるように継承元のクラスでself.logを定義した方がいい

2024-12-19 02:52 UTC, ivis-kondoKaho commented on data_gorvernance/library/main_menu/subflow_controller/create.py
> +        self.govsheet_path = os.path.join(self.abs_root, self.remote_path)
ガバナンスシート取得まではコメントがあるので、これ以降も同レベルでコメント付けて欲しい

2024-12-19 02:52 UTC, ivis-kondoKaho commented on data_gorvernance/library/main_menu/subflow_controller/create.py
> +            file.JsonFile(self.govsheet_rf_path).write(self.govsheet)
サブフローを作り直す処理の後にガバナンスシートを適用する処理が書いてあるのはおかしい

2024-12-19 02:52 UTC, ivis-kondoKaho commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +    if not grdm_connect.check_authorization(grdm_url, token):
通信する回数はできるだけ減らしたいので、
`if not token or not grdm_connect.check_authorization(grdm_url, token)`
がいいかな。判定は前から行われるので、順番は逆にしないように

2024-12-19 02:52 UTC, ivis-kondoKaho commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +    govsheet = {}
この定義なくていい

2024-12-19 02:52 UTC, ivis-kondoKaho commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +    active_dict = {}
ここでは空の辞書を定義する意味はないと思う

2024-12-19 02:52 UTC, ivis-kondoKaho commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +    update_dependent_task(dependent_id_list, sf_status.tasks)
tasksの型はlist（正確にはlist[SubflowTask]）なので、このあたりの関数の引数の型はlistにする

2024-12-19 02:52 UTC, ivis-kondoKaho commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +        return False
grdm_connect.check_permissionの返り値はboolだから
return grdm_connect.check_permission(base_url, token, project_id)
でいい

2024-12-19 02:52 UTC, ivis-kondoKaho commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +        return False
同様に
return grdm_connect.check_authorization(base_url, token)
でよい

2024-12-19 02:52 UTC, ivis-kondoKaho commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +    notebook_name_list = []
notebook_name_list が使われていないのでいらないなら消す

2024-12-20 00:22 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +                        self.research_flow_message.update_error('form', 'project_id_not_exist')
全て直しました

2024-12-20 00:22 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +                self.token_input.visible = False
削除しました

2024-12-20 00:23 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +                    if utils.check_grdm_access(self.grdm_url, token, project_id):
通信エラー処理入れました

2024-12-20 00:23 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +            vault = Vault()
削除しました

2024-12-20 00:23 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +        """パーソナルアクセストークンとプロジェクトIDが正しい形式で記入されているか確認するメソッドです。
指摘通り修正しました

2024-12-20 00:25 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +        """パーソナルアクセストークンとプロジェクトIDの接続確認をするメソッドです。
指摘通り修正しました

2024-12-20 00:25 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +                    self.display_input_box()
指摘通り修正しました

2024-12-20 00:25 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +                    self.display_input_box()
指摘通り修正しました

2024-12-20 00:27 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +            self.log.error(message)
指摘通り修正しました

2024-12-20 00:27 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +            self.govsheet = {}
指摘通り修正しました

2024-12-20 00:27 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +                self.project_id_input.visible = False
指摘通り修正しました

2024-12-20 00:27 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +def recreate_subflow(abs_root: str, govsheet_rf_path: str, govsheet_rf: str, govsheet: str, research_flow_dict: dict):
指摘通り修正しました

2024-12-20 00:28 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +                file.JsonFile(self.govsheet_rf_path).write(self.govsheet)
指摘通り修正しました

2024-12-20 00:28 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +            self.grdm.sync(self.token, self.grdm_url, self.project_id, path, self.abs_root)
指摘通り修正しました

2024-12-20 00:28 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +        """パーソナルアクセストークンとプロジェクトIDが取得できたかによって表示欄を変えるメソッドです。
指摘通り修正しました

2024-12-20 00:28 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/create.py
> +                    if utils.check_grdm_access(self.grdm_url, token, project_id):
指摘通り修正しました

2024-12-20 00:28 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/create.py
> +        self.new_create_subflow(
指摘通り修正しました

2024-12-20 00:29 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/create.py
> +                    utils.validate_input_project_id(project_id)
指摘通り修正しました

2024-12-20 00:33 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/create.py
> +            self._err_output.update_error(message)
base.pyに定義しました。main.pyのcallback_submit_buttonメソッドのlog出力部分の修正もしました

2024-12-20 00:34 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/create.py
> +        self.govsheet_path = os.path.join(self.abs_root, self.remote_path)
指摘通り修正しました

2024-12-20 00:34 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +    if not grdm_connect.check_authorization(grdm_url, token):
指摘通り修正しました

2024-12-20 00:34 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +    govsheet = {}
指摘通り修正しました

2024-12-20 00:34 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +    active_dict = {}
指摘通り修正しました

2024-12-20 00:34 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +    update_dependent_task(dependent_id_list, sf_status.tasks)
list[SubflowTask]にしました

2024-12-20 00:35 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +        return False
指摘通り修正しました

2024-12-20 00:35 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +        return False
指摘通り修正しました

2024-12-20 00:35 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +    notebook_name_list = []
指摘通り修正しました

2024-12-20 06:00 UTC, ivis-kondoKaho requested changes
レビューしました。修正お願いします。

2024-12-20 09:22 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +        for sub_flow_id, sub_flow_name in subflow_data.items():
for文を1つにしてsub_flow_idだったところをsubflow_data['id']にしました

2024-12-20 09:23 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +            if filename.startswith('.ipynb'):
後方一致にしました
その後のパスの指定も違ったので修正しました

2024-12-20 09:24 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/create.py
> +            return
指摘通り修正しました

2024-12-20 09:24 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/create.py
> +        self.grdm = grdm.Grdm()
指摘通り修正しました

2024-12-20 09:24 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/subflow_controller/utils.py
> +
指摘通り修正しました

2024-12-20 09:24 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +        self.grdm = grdm.Grdm()
指摘通り修正しました

2024-12-20 09:24 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +from library.utils.error import InputWarning, UnusableVault, ProjectNotExist, RepoPermissionError, UnauthorizedError
指摘通り修正しました

2024-12-20 09:24 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +            return
入力欄が表示されているを条件としていれました

2024-12-20 09:24 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +        """パーソナルアクセストークン及びプロジェクトIDを入力してガバナンスシート適用をするメソッドです。
入力されたパーソナルアクセストークン及びプロジェクトIDで
にしました

2024-12-20 09:25 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +            raise
削除しました

2024-12-20 09:25 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +        """ガバナンスシート適用ボタンを押下してガバナンスシートを適用するメソッドです。
指摘通り修正しました

2024-12-20 09:25 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +            self.log.error(f'{message}\n{traceback.format_exc()}')
削除しました

2024-12-20 09:25 UTC, vas-fujinami commented on data_gorvernance/library/main_menu/main.py
> +            self.log.error(message)
必要なところだけ囲う修正して満足してました。通信の考慮入れました

2024-12-23 06:27 UTC, ivis-kondoKaho requested changes
修正お願いします。

2024-12-23 06:27 UTC, ivis-kondoKaho commented on data_governance/researchflow/task_mapping.json
> +{
ここのファイルだけど、設計書に記述例はあるけど、実際にどんな値でやるかは決まっていないので、内容は削除しておく

2024-12-23 08:50 UTC, vas-fujinami commented on data_governance/library/main_menu/main.py
> +            message = msg_config.get('form', 'project_id_not_exist').format(project_id)
self.project_id_input.value_inputにしました

2024-12-23 08:50 UTC, vas-fujinami commented on data_governance/library/main_menu/main.py
> +            self.abs_root, self.govsheet_rf_path, self.govsheet_rf, self.govsheet, self.research_flow_dict)
govsheet_rfとgovsheetをインスタンス変数からローカル変数にしました

2024-12-23 08:51 UTC, vas-fujinami commented on data_governance/researchflow/task_mapping.json
> +{
指摘通り修正しました

2024-12-24 04:28 UTC, ivis-kondoKaho approved these changes
レビューしました。指摘ありません。

2024-12-24 04:38 UTC, merged